version: "3"
services:
  db:
    image: postgres:11.5
    env_file:
      - ./docker/environments/db.env
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    env_file:
      - ./docker/environments/db.env
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/srv/habit-dungeon
    ports:
      - 3000:3000
    depends_on:
      - db
  web:
    build:
      context: docker/web
    volumes:
      - ./log:/var/log/nginx
    depends_on:
      - app
    ports:
      - 80:80
