version: "3"
services:
  db:
    image: postgres:11.5
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/srv/habit-dungeon:cached
      - bundle:/usr/local/bundle:cached
      - yarn-cache:/usr/local/share/.cache/yarn/v2:cached
      - node_modules:/srv/habit-dungeon/node_modules:cached
    ports:
      - 3000:3000
    depends_on:
      - db
  web:
    build:
      context: docker/web
    volumes:
      - ./log:/var/log/nginx
    depends_on:
      - app
    ports:
      - 80:80
volumes:
  bundle:
  yarn-cache:
  node_modules:
